
// This file has been generated by the GUI designer. Do not modify.
namespace Auto606
{
	public partial class VentanaPrincipal
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Auto606.VentanaPrincipal
			this.Name = "Auto606.VentanaPrincipal";
			this.Title = global::Mono.Unix.Catalog.GetString("VentanaPrincipal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
